In [18]:
# Dependencies
import pandas as pd
import numpy as np

In [19]:
# Store filepath in a variable
df = pd.read_csv("Resources/cleaned_data.csv")

df.columns.tolist()

['RA',
 'Project',
 'PID',
 'Arm',
 'Week',
 'Target',
 'Production',
 'Prod_Word_Dur',
 'Prod_Arpabet',
 'Word_ID',
 'Session_ID',
 'Prod_Word_N',
 'Prod_Phon_N',
 'PIDSESS_Code',
 'WordPhon_Code',
 'Phon_Sess_Code',
 'Word_Sess_Code',
 'Prod_Last_Phon',
 'Prod_Word_IPA',
 'Prod_Phon_IPA',
 'Prod_Phoneme_ID',
 'Target_Arpabet',
 'Target_N_Tot_Words',
 'Target_Word_IPA',
 'Target_N_Tot_Syllables',
 'Target_N_Tot_Characters',
 'Target_Phon_Arpabet',
 'Target_Phoneme_ID',
 'Target_Syll_Env',
 'Target_Word_Pos',
 'Syllable_NumID',
 'Target_Word_NumID',
 'Target_Con_Cluster',
 'Target_Clust_ID',
 'Target_Clus_Type',
 'Target_Clust_Phon_Pos',
 'Target_Clust_Phon_Env',
 'Target_Phon_IPA',
 'Prod_syllabic',
 'Prod_consonantal',
 'Prod_sonorant',
 'Prod_continuant',
 'Prod_delayed release',
 'Prod_approximant',
 'Prod_tap',
 'Prod_nasal',
 'Prod_voice',
 'Prod_spread gl',
 'Prod_constr gl',
 'Prod_labial',
 'Prod_round',
 'Prod_labiodental',
 'Prod_coronal',
 'Prod_anterior',
 'Prod_distributed',
 'Prod_strident',
 'Prod_lateral',
 'Prod_dorsal',
 'Prod_high',
 'Prod_low',
 'Prod_front',
 'Prod_back',
 'Prod_tense',
 'Prod_lax',
 'Prod_vowel',
 'Prod_consonant',
 'Prod_diphthong',
 'Prod_monophthong',
 'Prod_velar',
 'Prod_alveolar',
 'Prod_post-alveolar',
 'Prod_dental',
 'Prod_palatal',
 'Prod_glottal',
 'Prod_stop',
 'Prod_fricative',
 'Prod_affricate',
 'Prod_glide',
 'Prod_Place',
 'Prod_Manner',
 'Prod_Place_N',
 'Prod_Manner_N',
 'Prod_Height',
 'Prod_Frontness',
 'Prod_Height_N',
 'Prod_Frontness_N',
 'Target_syllabic',
 'Target_consonantal',
 'Target_sonorant',
 'Target_continuant',
 'Target_delayed release',
 'Target_approximant',
 'Target_tap',
 'Target_nasal',
 'Target_voice',
 'Target_spread gl',
 'Target_constr gl',
 'Target_labial',
 'Target_round',
 'Target_labiodental',
 'Target_coronal',
 'Target_anterior',
 'Target_distributed',
 'Target_strident',
 'Target_lateral',
 'Target_dorsal',
 'Target_high',
 'Target_low',
 'Target_front',
 'Target_back',
 'Target_tense',
 'Target_lax',
 'Target_vowel',
 'Target_consonant',
 'Target_diphthong',
 'Target_monophthong',
 'Target_velar',
 'Target_alveolar',
 'Target_post-alveolar',
 'Target_dental',
 'Target_palatal',
 'Target_glottal',
 'Target_stop',
 'Target_fricative',
 'Target_affricate',
 'Target_glide',
 'Target_Place',
 'Target_Manner',
 'Target_Place_N',
 'Target_Manner_N',
 'Target_Height',
 'Target_Frontness',
 'Target_Height_N',
 'Target_Frontness_N',
 'redcap_event_name',
 'wab1_aq',
 'wab1_ss_total',
 'wab1_avc_total',
 'wab1_r_total',
 'wab1_nwf_total',
 'wabaq_start']

In [20]:
#Make a dataframe to store accuracy scores
acc_scores = (
    df[[
        'RA',
        'PID',
        'Arm',
        'Week',
        'redcap_event_name',
        'Target',
        'Word_ID',
        'Production',
        'Prod_Arpabet',
        'Prod_Word_N',
        'Prod_Phon_N',
        'Prod_Word_IPA',
        'Prod_Phon_IPA',
        'Prod_Phoneme_ID',
        'Prod_voice',
        'Prod_Place',
        'Prod_Manner',
        'Prod_tense',
        'Prod_round',
        'Prod_Height',
        'Prod_Frontness',        
        'Target_Arpabet',
        'Target_Word_IPA',
        'Target_N_Tot_Characters',
        'Target_Phon_Arpabet',
        'Target_Phoneme_ID',
        'Target_Word_NumID',
        'Target_Phon_IPA',
        'Target_voice',
        'Target_Place',
        'Target_Manner',
        'Target_tense',
        'Target_round',
        'Target_Height',
        'Target_Frontness',
        'wab1_aq',
        'wab1_ss_total',
        'wab1_avc_total',
        'wab1_r_total',
        'wab1_nwf_total',
        'wabaq_start'
        ]]
        ).copy()

In [21]:
# apply function to calculate voicing accuracy
acc_scores['Phon_Acc'] = df.apply(lambda x: 1 if x['Prod_Phoneme_ID'] == x['Target_Phoneme_ID'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,Target_round,Target_Height,Target_Frontness,wab1_aq,wab1_ss_total,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,-1,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,1,high,back,67.8,15,9.8,5.3,3.8,61-70,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,-1,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,-1,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,1,mid-low,back,67.8,15,9.8,5.3,3.8,61-70,1

In [22]:
# apply function to calculate voicing accuracy
acc_scores['Voicing_Acc'] = df.apply(lambda x: 1 if x['Prod_voice'] == x['Target_voice'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,Target_Height,Target_Frontness,wab1_aq,wab1_ss_total,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,high,back,67.8,15,9.8,5.3,3.8,61-70,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,consonant,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,mid-low,back,67.8,15,9.8,5.3,3.8,61-70,1,1

In [23]:
# apply function to calculate place accuracy
acc_scores['Place_Acc'] = df.apply(lambda x: 1 if x['Prod_Place_N'] == x['Target_Place_N'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,Target_Frontness,wab1_aq,wab1_ss_total,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,back,67.8,15,9.8,5.3,3.8,61-70,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,consonant,67.8,15,9.8,5.3,3.8,61-70,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,back,67.8,15,9.8,5.3,3.8,61-70,1,1,1

In [24]:
# apply function to calculate manner accuracy
acc_scores['Manner_Acc'] = df.apply(lambda x: 1 if x['Prod_Manner_N'] == x['Target_Manner_N'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,wab1_aq,wab1_ss_total,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,67.8,15,9.8,5.3,3.8,61-70,1,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,67.8,15,9.8,5.3,3.8,61-70,1,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,67.8,15,9.8,5.3,3.8,61-70,1,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,67.8,15,9.8,5.3,3.8,61-70,1,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,67.8,15,9.8,5.3,3.8,61-70,1,1,1,1

In [25]:
# apply function to calculate height accuracy
acc_scores['Height_Acc'] = df.apply(lambda x: 1 if x['Prod_Height_N'] == x['Target_Height_N'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,wab1_ss_total,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc,Height_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,15,9.8,5.3,3.8,61-70,1,1,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,15,9.8,5.3,3.8,61-70,1,1,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,15,9.8,5.3,3.8,61-70,1,1,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,15,9.8,5.3,3.8,61-70,1,1,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,15,9.8,5.3,3.8,61-70,1,1,1,1,1

In [26]:
# apply function to calculate frontness accuracy
acc_scores['Frontness_Acc'] = df.apply(lambda x: 1 if x['Prod_Frontness_N'] == x['Target_Frontness_N'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,wab1_avc_total,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc,Height_Acc,Frontness_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,9.8,5.3,3.8,61-70,1,1,1,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,9.8,5.3,3.8,61-70,1,1,1,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,9.8,5.3,3.8,61-70,1,1,1,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,9.8,5.3,3.8,61-70,1,1,1,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,9.8,5.3,3.8,61-70,1,1,1,1,1,1

In [27]:
# apply function to calculate tenseness accuracy
acc_scores['Tenseness_Acc'] = df.apply(lambda x: 1 if x['Prod_tense'] == x['Target_tense'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,wab1_r_total,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc,Height_Acc,Frontness_Acc,Tenseness_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,5.3,3.8,61-70,1,1,1,1,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,5.3,3.8,61-70,1,1,1,1,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,5.3,3.8,61-70,1,1,1,1,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,5.3,3.8,61-70,1,1,1,1,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,5.3,3.8,61-70,1,1,1,1,1,1,1

In [28]:
# apply function to calculate roundness accuracy
acc_scores['Roundness_Acc'] = df.apply(lambda x: 1 if x['Prod_round'] == x['Target_round'] else 0, axis=1)
acc_scores.head()

,RA,PID,Arm,Week,redcap_event_name,Target,Word_ID,Production,Prod_Arpabet,Prod_Word_N,...,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc,Height_Acc,Frontness_Acc,Tenseness_Acc,Roundness_Acc
0,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,B,1,...,3.8,61-70,1,1,1,1,1,1,1,1
1,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,UH,1,...,3.8,61-70,1,1,1,1,1,1,1,1
2,DS,15,1,Baseline,arm_1_baseline_arm_1,book,1,B UH K,K,1,...,3.8,61-70,1,1,1,1,1,1,1,1
3,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,B,2,...,3.8,61-70,1,1,1,1,1,1,1,1
4,DS,15,1,Baseline,arm_1_baseline_arm_1,ball,2,B AO L,AO,2,...,3.8,61-70,1,1,1,1,1,1,1,1

In [29]:
#Save accuracy scores
acc_scores.to_csv("Resources/acc_scores-v2.csv", index=False, header=True)

In [30]:
#Do the same thing for the df
df['Phon_Acc'] = df.apply(lambda x: 1 if x['Prod_Phoneme_ID'] == x['Target_Phoneme_ID'] else 0, axis=1)
df['Voicing_Acc'] = df.apply(lambda x: 1 if x['Prod_voice'] == x['Target_voice'] else 0, axis=1)
df['Place_Acc'] = df.apply(lambda x: 1 if x['Prod_Place_N'] == x['Target_Place_N'] else 0, axis=1)
df['Manner_Acc'] = df.apply(lambda x: 1 if x['Prod_Manner_N'] == x['Target_Manner_N'] else 0, axis=1)
df['Height_Acc'] = df.apply(lambda x: 1 if x['Prod_Height_N'] == x['Target_Height_N'] else 0, axis=1)
df['Frontness_Acc'] = df.apply(lambda x: 1 if x['Prod_Frontness_N'] == x['Target_Frontness_N'] else 0, axis=1)
df['Tenseness_Acc'] = df.apply(lambda x: 1 if x['Prod_tense'] == x['Target_tense'] else 0, axis=1)
df['Roundness_Acc'] = df.apply(lambda x: 1 if x['Prod_round'] == x['Target_round'] else 0, axis=1)
df.head()

,RA,Project,PID,Arm,Week,Target,Production,Prod_Word_Dur,Prod_Arpabet,Word_ID,...,wab1_nwf_total,wabaq_start,Phon_Acc,Voicing_Acc,Place_Acc,Manner_Acc,Height_Acc,Frontness_Acc,Tenseness_Acc,Roundness_Acc
0,DS,rPPA,15,1,Baseline,book,B UH K,0.295646,B,1,...,3.8,61-70,1,1,1,1,1,1,1,1
1,DS,rPPA,15,1,Baseline,book,B UH K,0.295646,UH,1,...,3.8,61-70,1,1,1,1,1,1,1,1
2,DS,rPPA,15,1,Baseline,book,B UH K,0.295646,K,1,...,3.8,61-70,1,1,1,1,1,1,1,1
3,DS,rPPA,15,1,Baseline,ball,B AO L,0.397365,B,2,...,3.8,61-70,1,1,1,1,1,1,1,1
4,DS,rPPA,15,1,Baseline,ball,B AO L,0.397365,AO,2,...,3.8,61-70,1,1,1,1,1,1,1,1

In [31]:
#Save the aggregated dataframe
df.to_csv("Resources/baseline_data_pvm_acc.csv", index=False, header=True)